train: "C:/Users/User/Desktop/tree_images_and_annotations/train/images"
val: "C:/Users/User/Desktop/tree_images_and_annotations/valid/images"
test: "C:/Users/User/Desktop/tree_images_and_annotations/test/images"

names:
  0: root
  1: trunk
  2: canopy
# In the YOLO training configuration file
class_weights: [3.0, 1.0, 1.0]  # Increase weight for the root class
lr0: 0.001  # Initial learning rate
lrf: 0.01   # Final learning rate
batch_size: 16

